---
name: coffee_shop_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.4.0
  lottie: ^3.0.0
  icons_plus: ^5.0.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  animated_snack_bar: ^0.4.0
  awesome_dialog: ^3.2.0
  google_sign_in: ^6.2.1
  flutter_screenutil: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  translator_plus: ^1.0.1
  percent_indicator: ^4.2.3
  animated_digit: ^3.2.3
  avs_image: ^1.0.1
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  flutter_svg_provider: ^1.0.7

dev_dependencies:
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - Assets/Animations/
    - Assets/Images/
    - Assets/Fonts/
  fonts:
    - family: Marsmonster
      fonts:
        - asset: Assets/Fonts/MarsmonsterDemo-Regular.ttf
