// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdDClvfhKmIwvw6x3R0iXmP39zkca-r5M',
    appId: '1:669010270124:web:4c73571eda6a596f9e8c09',
    messagingSenderId: '669010270124',
    projectId: 'qahwatuna-app',
    authDomain: 'qahwatuna-app.firebaseapp.com',
    storageBucket: 'qahwatuna-app.appspot.com',
    measurementId: 'G-TBJSQ4Z70P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsWd3tlFFCXylX8DVApXwXScx1em_IDQU',
    appId: '1:669010270124:android:cfbadda6274d85199e8c09',
    messagingSenderId: '669010270124',
    projectId: 'qahwatuna-app',
    storageBucket: 'qahwatuna-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaI_yRv0Ptn6d1L3wuJVVu0TxdLbpw3bc',
    appId: '1:669010270124:ios:b546bf2ccc8f1dda9e8c09',
    messagingSenderId: '669010270124',
    projectId: 'qahwatuna-app',
    storageBucket: 'qahwatuna-app.appspot.com',
    iosBundleId: 'com.example.coffeeShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaI_yRv0Ptn6d1L3wuJVVu0TxdLbpw3bc',
    appId: '1:669010270124:ios:f7364a1142a1112f9e8c09',
    messagingSenderId: '669010270124',
    projectId: 'qahwatuna-app',
    storageBucket: 'qahwatuna-app.appspot.com',
    iosBundleId: 'com.example.coffeeShopApp.RunnerTests',
  );
}
